name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PERSONAL_KEY }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build -t ruxwez/postgres:$IMAGE_TAG .
        docker tag ruxwez/postgres:$IMAGE_TAG ruxwez/postgres:latest
        docker push ruxwez/postgres:$IMAGE_TAG
        docker push ruxwez/postgres:latest
